### ISSUE TITLE
hass logs spammed with: Packet type 7 not implemented. Ignoring!

### ISSUE THREAD

**Issue by Luap99** [lkempf/casambi-bt#15]
I See the following warning a lot in my home assistant logs, about 500 times in a short time frame (some minutes)
``
WARNING (MainThread) [CasambiBt._client] Packet type 7 not implemented. Ignoring!
```

I am not sure what packet type this is but it doesn't seems to cause any problems for me so maybe we should lower this message to debug/info level instead?

**Comment by lkempf** [comment]
Sounds reasonable. I only had this on warning because it only ever happened (with type 6) when a connection was established for me.
