### ISSUE TITLE
Error on CasambiBt import

### ISSUE THREAD

**Issue by aschwith** [lkempf/casambi-bt#19]
Importing the CasambiBt package via

`from CasambiBt import Casambi, discover`

results in an error:

Datei '/home/smarthome/.local/lib/python3.8/site-packages/CasambiBt/errors.py', Zeile 14
   function ConnectionStateError(), Exception: unsupported operand type(s) for |: 'type' and 'NoneType'

Test is run under python 3.8.6.

Any help is appreciated. Thanks and best regards

**Comment by lkempf** [comment]
Python 3.9 or newer is required.

**Comment by aschwith** [comment]
All right. Thanks!
