### ISSUE TITLE
Store network data in .storage folder

### ISSUE THREAD

**Issue by CFenner** [lkempf/casambi-bt#21]
**Is your feature request related to a problem? Please describe.**
It would be nice it the casambi integration would store it's data in the `/config/.storage` folder for a better overview.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lkempf** [comment]
I've added some logic to detect whether the library has been loaded via HA. The cache folder is changed in that case. This still needs a bit more testing but I should get it released before christmas

**Comment by CFenner** [comment]
This could also be a parameter set on init from HA if auto detection is complicated.

**Comment by lkempf** [comment]
Thanks for the tip. After some testing and discovering that HA has an API for getting the config folder I'm going to switch to that approach. Using cwd doesn't seem that robust.
