### ISSUE TITLE
State de-/encoding broken in some cases

### ISSUE THREAD

**Issue by mintnl** [lkempf/casambi-bt#9]
Thanx for this integration!

All light are being detected OK and work fine with on/off. However is the percentage of brightness is changed it seems that the values are screwed up somehow.

If i raise brightness in the casambi APP to say 17%, HA does the same thing 17%. Perfect.
If i raise brightness in the casambi APP to say 37%, HA sets the slider to 12%. (subtracts 25)
If i raise brightness in the casambi APP to say 57%, HA sets the slider to 7%. (subtracts 50)
If i raise brightness in the casambi APP to say 77%, HA sets the slider to 2%. (subtracts 75)

The other way around will always set the slider to a value to or below 25%. Everything above will trigger an error
`byte must be in range(0, 256)`

I use several LEDs GO BL-TED & Casambi CBU-TED dimmers (same) that do have this issue, they operate 230V lights
I also have a Casambi CBU-PWM4 Ledstrip dimmer and a TCI dimmer that don't have this issue.

**Comment by lkempf** [comment]
I think I have fixed the issue but the fix needs some more testing to make sure I haven't broken anything else.

**Comment by mintnl** [comment]
Somehow it has to do with the COLORMODE_BRIGHTNESS (0 to 255) and COLORMODE_BRIGHTNESS_PCT (0 to 100)
Whereas the dimmer reports the percentage 0-100 instead of the expected 0-255?

I will test it, thank you

**Comment by lkempf** [comment]
No I'm quite sure the issue was that I handled the 2 bits of overheat information before the dimmer value incorrectly. Due to this the highest 2 bits of the dimmer value weren't handled correctly and either disappeared (value in HA to low) or caused some internal value that should be a byte to have 2 additional bits (causing the ValueError). 

I don't think you actually want to test the changes yourself until I create a release unless you want to setup a whole development setup. I'm going to visit my parents next week so I can just test it then.

**Comment by mintnl** [comment]
> I don't think you actually want to test the changes yourself until I create a release unless you want to setup a whole development setup. I'm going to visit my parents next week so I can just test it then. The 2 luminaries you had issues with should be fixed as far as I could test from the information in the logs.

You're right. Want to test if you create a new release (maybe a beta?) :-)
I have about about 20 dimmers in use, 18 are the casambi-TED which all have this issue (cause they're all the same sort :-) )

Thanx for your effort!

**Comment by lkempf** [comment]
I can create a completely untested pre-release if you want. That shouldn't be a lot of work.

**Comment by lkempf** [comment]
You should be able to update the integration to the current state of the main branch in HACS now. I won't guarantee that this update won't break something though.

**Comment by mintnl** [comment]
> I can create a completely untested pre-release if you want. That shouldn't be a lot of work.

Thank you for your effort!



> You should be able to update the integration to the current state of the main branch in HACS now. I won't guarantee that this update won't break something though.

I selected version "main" on redownloading the integration, but after a restart the integration fails to load the network. :-s

**Comment by lkempf** [comment]
I think I found that issue. Everything seems to be working fine for my test devices so I will publish the new version the next couple of days. You can try updating to main again to see if I fixed it for you.

**Comment by mintnl** [comment]
While using "main"  version the network is not detected correctly:

> 2023-02-21 17:13:40.306 INFO (MainThread) [homeassistant.setup] Setting up casambi_bt
> 2023-02-21 17:13:40.306 INFO (MainThread) [homeassistant.setup] Setup of domain casambi_bt took 0.0 seconds
> 2023-02-21 17:13:40.310 ERROR (MainThread) [custom_components.casambi_bt] Unexpected error creating network 03:19:XX:XX:XX:XX
> File "/config/custom_components/casambi_bt/__init__.py", line 80, in async_casmbi_api_setup

**Comment by lkempf** [comment]
Did you redownload main? It doesn't get updated automatically and HACS doesn't show update hints for main.

**Comment by mintnl** [comment]
HACS > Casambi Bluetooth > three dots in the top right > redownload > selected "main" instead of 0.0.5 .

**Comment by lkempf** [comment]
Can you give me the full log in that case? I think the error you gave me is cut off and I can't reproduce your issue.

**Comment by Synasenn** [comment]
Also works perfectly for me. Thanks a lot!
